[helpers]

[default]
depends = []

[default.files]
bat = "~/.config/bat"
fish = "~/.config/fish"
glamour = "~/.config/glamour"
glow = "~/.config/glow"
lazygit = "~/.config/lazygit"
nvim = "~/.config/nvim"
ranger = "~/.config/ranger"
starship = "~/.config"
zellij = "~/.config/zellij"
tmux = "~"
wezterm = "~/.config"

[default.variables]
